"""create tables

Revision ID: c8a9825fc357
Revises: 
Create Date: 2022-07-31 18:37:36.907128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a9825fc357'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('parent_id', sa.SmallInteger(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('name_en', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('media', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total', sa.SmallInteger(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('name_en', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_users',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.SmallInteger(), nullable=True),
    sa.Column('language_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
     )
    op.create_table('orders',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('bot_user_id', sa.SmallInteger(), nullable=False),
    sa.Column('date_create', sa.TIMESTAMP(), nullable=True),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.Column('invoice_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['bot_user_id'], ['bot_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
     )
    op.create_table('order_items',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('order_id', sa.SmallInteger(), nullable=False),
    sa.Column('product_id', sa.SmallInteger(), nullable=False),
    sa.Column('total', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )               
    op.create_table('invoices',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('bot_user_id', sa.SmallInteger(), nullable=False),
    sa.Column('date_create', sa.TIMESTAMP(), nullable=True),
    sa.Column('total', sa.SmallInteger(), nullable=True),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['bot_user_id'], ['bot_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=24), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('products')
    op.drop_table('bot_users')
    op.drop_table('users')
    op.drop_table('statuses')
    op.drop_table('orders')
    op.drop_table('languages')
    op.drop_table('invoices')
    op.drop_table('categories')
    # ### end Alembic commands ###
